services:
  nodejs:
    build: .
    container_name: nodejs
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
